export const NAVIGATED = "NAVIGATED"; // used to update the title shown in the header

// root level
export const APP_DATA = "APP_DATA";
export const APP_DATA_SUCCESS = "APP_DATA_SUCCESS";
export const APP_DATA_ERROR = "APP_DATA_ERROR";
export const APP_FRAME = "APP_FRAME";
export const APP_FRAME_UNMOUNTED = "APP_FRAME_UNMOUNTED";

// home
export const HOME_PAGE = "HOME_PAGE";
export const HOME_PAGE_UNMOUNTED = "HOME_PAGE_UNMOUNTED";

export const CURRENT_VERSION_PAGE = "CURRENT_VERSION_PAGE";
export const CURRENT_VERSION_PAGE_UNMOUNTED = "CURRENT_VERSION_PAGE_UNMOUNTED";
export const CURRENT_VERSION_DATA = "CURRENT_VERSION_DATA";
export const CURRENT_VERSION_DATA_SUCCESS = "CURRENT_VERSION_DATA_SUCCESS";
export const CURRENT_VERSION_DATA_ERROR = "CURRENT_VERSION_DATA_ERROR";

export const TRANSACTIONS_LOG_PAGE = "TRANSACTIONS_LOG_PAGE";
export const TRANSACTIONS_LOG_PAGE_UNMOUNTED = "TRANSACTIONS_LOG_PAGE_UNMOUNTED";
export const TRANSACTIONS_LOG_DATA = "TRANSACTIONS_LOG_DATA";
export const TRANSACTIONS_LOG_DATA_SUCCESS = "TRANSACTIONS_LOG_DATA_SUCCESS";
export const TRANSACTIONS_LOG_DATA_ERROR = "TRANSACTIONS_LOG_DATA_ERROR";
